### ISSUE TITLE
Heroku Instance Throwing Errors

### ISSUE THREAD

**Issue by PeterMarcouillier** [dhuang612/shoutout#2]
Not an issue directly related to the codebase, but wanted to pass an FYI along that your "see a running application at:" [link](https://shoutouts-the-app.herokuapp.com/) is throwing errors on load, specifically: 
```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
```

**Comment by dhuang612** [comment]
Hi Peter,

Thank you for letting me know. I have resolved the issue.
https://shoutouts-the-app.herokuapp.com/

Have a great week!

Dan
